# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "St12bl3TfK+Twj4z5YPYMKCqHs9JIOjg90CAtg6PYR8gC6R+tPK0cHr0UfvX4RkX65oBnJEz1D+rPN8FSfRa+PNaOXMhuzcyNjdZnY1FD6Gq9FuqvQk1uR2mqCtUk4anp6IEpKNIPpLn4AE8Ds0KL0AJ2I3ua+qDnpTjEP7zmG41FYEUPJalHHrV0wseMvrHiDmzsKNXoURwKnScGvxegbuhmhaagN6IP5JIPJ/iHv13OpVn71pUm0p7ntWKZbREIzm/J6QtgX/lojSADvuNJHeLEg5nLgzf2ripVvopL9RhUSs/+RRKbiGw2FktKqGOjJ+aKW9uIjYoS/29/haiMTEqi4xvf3bisxzWq/cwfl2FK5PVOBBq0V50FagRaBDLKjqsPCUWB0DrvdU4E1haUcDlQz1QLEp9K7G6gJJ/+OpVobO26LzUxSYvOiFoYMEZDgmDPL+A/z63RL8j3v5UTzhG//69/lUM+4lqr2Q7Qj9rZrWgnCHcpywcJdpO8eIaUx/dzCkc+0SZHVXa5Pdk577vpoX9H2tvDTdotN8nssOA750jc3rm1bt5/KE1kdwn89KmETbYEN8wRID1F8sREFasFtDD4ok69WYQZ9Yx4QB4X9Ar7p0FJJLFKE/azZgjGRWcD6PbVfGZVBnuURAVhT78HFl7EsNNc4kG0y81rPM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml