travis:
  secure:
    BINSTAR_TOKEN: 30fSIN65vncDVv2o4IOEsj+kMMCqGvPOvheMPN0gUmpSQtjhUk/nCTGEeemVgk546gGo23K7KRImL6WKWLDMUAFsc85dcrOO/zx2rlMvLCKsZr1nbZzp3WVXNi/iOVa0QiJx6AkAPcaMYPXGmcUyfPXysSuONJIquS1aMLlqEXBEpuG3N8MysCiIz2R4eezoRLfTlQ/1nbqPGjx8ijIHiOSSZbIdG5GR0UC/gGQ8ZQ5j2ZPzkKcEdx56r/zmP8Va2M+3IP/AhZ0vGujlKuy/ayT3YYXPKYwTyWGP79cQkFUIVJIFC6Xg9R/Ubbwa0zbAba+xfzaU6j+WCzBkBztLPW3XJ1a3NDOzaJqRhTcs+OY0P/Fl29C98PG6GmbU9lncssZ5Y/v5deQ03mMVi/0Jfg7PBmNC7YgKbULw3C7zVOZQOVaYi0Uigv1KyxwrxpON97b3+T9smeZfp5bpOw4jylTkL6YoQVFoElMt5ngxqg2ipC9FG/EjpQz/gFufA9sCRhObTsCk4CyO3dV4oKRwOmhimgLy8/kVdx7dJEEz+xqdn/gbDPL+9VsrHo3MTV2eYLvmC+KMoSPTqgWYXnimn+T75Kx7ctmm1W/I+97Tmt5N2MvCjsq6rI9++BcNOGBGpedxShREpgxLcaaHhGiNOhDljBBi/lAXD2BwPRhCNww=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
