travis:
  secure:
    BINSTAR_TOKEN: St12bl3TfK+Twj4z5YPYMKCqHs9JIOjg90CAtg6PYR8gC6R+tPK0cHr0UfvX4RkX65oBnJEz1D+rPN8FSfRa+PNaOXMhuzcyNjdZnY1FD6Gq9FuqvQk1uR2mqCtUk4anp6IEpKNIPpLn4AE8Ds0KL0AJ2I3ua+qDnpTjEP7zmG41FYEUPJalHHrV0wseMvrHiDmzsKNXoURwKnScGvxegbuhmhaagN6IP5JIPJ/iHv13OpVn71pUm0p7ntWKZbREIzm/J6QtgX/lojSADvuNJHeLEg5nLgzf2ripVvopL9RhUSs/+RRKbiGw2FktKqGOjJ+aKW9uIjYoS/29/haiMTEqi4xvf3bisxzWq/cwfl2FK5PVOBBq0V50FagRaBDLKjqsPCUWB0DrvdU4E1haUcDlQz1QLEp9K7G6gJJ/+OpVobO26LzUxSYvOiFoYMEZDgmDPL+A/z63RL8j3v5UTzhG//69/lUM+4lqr2Q7Qj9rZrWgnCHcpywcJdpO8eIaUx/dzCkc+0SZHVXa5Pdk577vpoX9H2tvDTdotN8nssOA750jc3rm1bt5/KE1kdwn89KmETbYEN8wRID1F8sREFasFtDD4ok69WYQZ9Yx4QB4X9Ar7p0FJJLFKE/azZgjGRWcD6PbVfGZVBnuURAVhT78HFl7EsNNc4kG0y81rPM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
